### ISSUE TITLE
I2C pins for HTIT

### ISSUE THREAD

**Issue by sp9wpn** [pjalocha/ogn-tracker#5]
While Heltec did not label any pins as SDA/SCL, it is still possible to use few unassigned GPIOs for I2C communication. I've just tested BME280 with GPIOs 4 and 5. Is any "official" choice of such pins considered, so I can keep compatibility in the long run? #

**Comment by pjalocha** [comment]
There is no official assignment for the I2C pins on HTIT - if 4 and 5 work fine, we can use those, why not - so which is clock and which is data ?

If possible, the I2C pins should be easy to align on typical I2C modules with ground and power. For example on T-Beam you can solder BME280 module pin-to-pin thus keep it easy and solid.

**Comment by sp9wpn** [comment]
This board keeps all GND and V+ pins in a group, so it's not possible to design direct-soldering option. I'm using following pins ATM:
```
#define I2C_PinSDA 4
#define I2C_PinSCL 5
```
But I'm still in breadboard phase. Another working pair is 45 and 46. As they are digital-only, we won't "waste" ADC pins, such like 4 and 5.

**Comment by sp9wpn** [comment]
I've decided on 45/46 for I2C. GPIO4 can be used for external voltage measurement. Pull request following.
